import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


// add google font
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "E-market app",
  description: "Generated by kim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-neutral-900 text-white max-w-screen-sm m-auto`}>{children}</body>
    </html>
  );
}
